
---
--- Table: JOB8
---

INSERT INTO JOB8 (ID, VERSION, CDI_FILE, EXTERNAL_JOB_ID, HIDDEN, JOB_DIR, NAME, NUM_TIME_STEPS, PERCENTAGE, POWERFLOW_VERSION, RANK, SUBMISSION_TIME, SUMMARY_FLAG, TIME_STEP, TIME_TO_FINISH, TIME_TO_START, TYPE, USERNAME) VALUES 
    (1, 0, 'k', 1, false, 'k', 'k', 2, 1, 'jj', 1, '2014-06-09 00:00:00.0', false, 0, 99.0, 55.0, 1, 'gg');

INSERT INTO JOB8 (ID, VERSION, CDI_FILE, EXTERNAL_JOB_ID, HIDDEN, JOB_DIR, NAME, NUM_TIME_STEPS, PERCENTAGE, POWERFLOW_VERSION, RANK, SUBMISSION_TIME, SUMMARY_FLAG, TIME_STEP, TIME_TO_FINISH, TIME_TO_START, TYPE, USERNAME) VALUES 
    (2, 1, 'tt1', 1, false, 'ff', 'tg', 7, 1, 'jjj', 1, '2014-06-08 00:00:00.0', false, 0, 78.0, 34.0, 1, 'hjj');

INSERT INTO JOB8 (ID, VERSION, CDI_FILE, EXTERNAL_JOB_ID, HIDDEN, JOB_DIR, NAME, NUM_TIME_STEPS, PERCENTAGE, POWERFLOW_VERSION, RANK, SUBMISSION_TIME, SUMMARY_FLAG, TIME_STEP, TIME_TO_FINISH, TIME_TO_START, TYPE, USERNAME) VALUES 
    (4, 0, 'k', 1, false, 'k', 'k', 2, 1, 'jj', 1, '2014-06-07 00:00:00.0', false, 0, 99.0, 55.0, 1, 'gg');

INSERT INTO JOB8 (ID, VERSION, CDI_FILE, EXTERNAL_JOB_ID, HIDDEN, JOB_DIR, NAME, NUM_TIME_STEPS, PERCENTAGE, POWERFLOW_VERSION, RANK, SUBMISSION_TIME, SUMMARY_FLAG, TIME_STEP, TIME_TO_FINISH, TIME_TO_START, TYPE, USERNAME) VALUES 
    (5, 1, 'tt1', 1, false, 'ff', 'tg', 5, 1, 'jjj', 1, '2014-05-29 00:00:00.0', false, 0, 78.0, 34.0, 1, 'hjj');

INSERT INTO JOB8 (ID, VERSION, CDI_FILE, EXTERNAL_JOB_ID, HIDDEN, JOB_DIR, NAME, NUM_TIME_STEPS, PERCENTAGE, POWERFLOW_VERSION, RANK, SUBMISSION_TIME, SUMMARY_FLAG, TIME_STEP, TIME_TO_FINISH, TIME_TO_START, TYPE, USERNAME) VALUES 
    (6, 0, 'cdi file1', 1, false, 'jd2', 'n3', 1, 1, 'pv4', 1, '2014-05-19 00:00:00.002', false, 0, 12.0, 345.0, 1, 'usn11');

INSERT INTO JOB8 (ID, VERSION, CDI_FILE, EXTERNAL_JOB_ID, HIDDEN, JOB_DIR, NAME, NUM_TIME_STEPS, PERCENTAGE, POWERFLOW_VERSION, RANK, SUBMISSION_TIME, SUMMARY_FLAG, TIME_STEP, TIME_TO_FINISH, TIME_TO_START, TYPE, USERNAME) VALUES 
    (7, 0, 'k', 1, false, 'k', 'k', 2, 1, 'jj', 1, '2014-04-09 00:00:00.0', false, 0, 99.0, 55.0, 1, 'gg');

INSERT INTO JOB8 (ID, VERSION, CDI_FILE, EXTERNAL_JOB_ID, HIDDEN, JOB_DIR, NAME, NUM_TIME_STEPS, PERCENTAGE, POWERFLOW_VERSION, RANK, SUBMISSION_TIME, SUMMARY_FLAG, TIME_STEP, TIME_TO_FINISH, TIME_TO_START, TYPE, USERNAME) VALUES 
    (8, 0, 'tt1', 1, false, 'ff', 'tg', 1, 1, 'jjj', 1, '2014-04-15 00:00:00.0', false, 0, 78.0, 34.0, 1, 'hjj');

INSERT INTO JOB8 (ID, VERSION, CDI_FILE, EXTERNAL_JOB_ID, HIDDEN, JOB_DIR, NAME, NUM_TIME_STEPS, PERCENTAGE, POWERFLOW_VERSION, RANK, SUBMISSION_TIME, SUMMARY_FLAG, TIME_STEP, TIME_TO_FINISH, TIME_TO_START, TYPE, USERNAME) VALUES 
    (9, 0, 'cdi file1', 1, false, 'jd2', 'n3', 1, 1, 'pv4', 1, '2014-02-09 00:00:00.0', false, 0, 12.0, 345.0, 1, 'usn11');

INSERT INTO JOB8 (ID, VERSION, CDI_FILE, EXTERNAL_JOB_ID, HIDDEN, JOB_DIR, NAME, NUM_TIME_STEPS, PERCENTAGE, POWERFLOW_VERSION, RANK, SUBMISSION_TIME, SUMMARY_FLAG, TIME_STEP, TIME_TO_FINISH, TIME_TO_START, TYPE, USERNAME) VALUES 
    (11, 0, 'k', 1, false, 'k', 'k', 2, 1, 'jj', 1, '2014-01-09 00:00:00.0', false, 0, 99.0, 55.0, 1, 'gg');

INSERT INTO JOB8 (ID, VERSION, CDI_FILE, EXTERNAL_JOB_ID, HIDDEN, JOB_DIR, NAME, NUM_TIME_STEPS, PERCENTAGE, POWERFLOW_VERSION, RANK, SUBMISSION_TIME, SUMMARY_FLAG, TIME_STEP, TIME_TO_FINISH, TIME_TO_START, TYPE, USERNAME) VALUES 
    (12, 0, 'tt1', 1, false, 'ff', 'tg', 1, 1, 'jjj', 1, '2014-02-09 00:00:00.0', false, 0, 78.0, 34.0, 1, 'hjj');

INSERT INTO JOB8 (ID, VERSION, CDI_FILE, EXTERNAL_JOB_ID, HIDDEN, JOB_DIR, NAME, NUM_TIME_STEPS, PERCENTAGE, POWERFLOW_VERSION, RANK, SUBMISSION_TIME, SUMMARY_FLAG, TIME_STEP, TIME_TO_FINISH, TIME_TO_START, TYPE, USERNAME) VALUES 
    (13, 0, 'cdi file1', 1, false, 'jd2', 'n3', 1, 1, 'pv4', 1, '2014-01-19 00:00:00.0', false, 0, 12.0, 345.0, 1, 'usn11');

INSERT INTO JOB8 (ID, VERSION, CDI_FILE, EXTERNAL_JOB_ID, HIDDEN, JOB_DIR, NAME, NUM_TIME_STEPS, PERCENTAGE, POWERFLOW_VERSION, RANK, SUBMISSION_TIME, SUMMARY_FLAG, TIME_STEP, TIME_TO_FINISH, TIME_TO_START, TYPE, USERNAME) VALUES 
    (33, 0, 'cdi file1', 1, false, 'jd2', 'n3', 1, 1, 'pv4', 1, '2014-03-09 00:00:00.0', false, 0, 12.0, 345.0, 1, 'usn11');

