
---
--- Table: JOB8
---

CREATE TABLE PUBLIC.JOB8 (
    ID BIGINT(19) DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_A3F90B8C_3715_4910_BB67_2B51C748610B) NOT NULL,
    VERSION BIGINT(19) NOT NULL,
    CDI_FILE VARCHAR(255) NOT NULL,
    EXTERNAL_JOB_ID BIGINT(19) NOT NULL,
    HIDDEN BOOLEAN NOT NULL,
    JOB_DIR VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    NUM_TIME_STEPS BIGINT(19) NOT NULL,
    PERCENTAGE BIGINT(19) NOT NULL,
    POWERFLOW_VERSION VARCHAR(255) NOT NULL,
    RANK INT(10) NOT NULL,
    SUBMISSION_TIME TIMESTAMP NOT NULL,
    SUMMARY_FLAG BOOLEAN NOT NULL,
    TIME_STEP BIGINT(19) NOT NULL,
    TIME_TO_FINISH DOUBLE(17) NOT NULL,
    TIME_TO_START DOUBLE(17) NOT NULL,
    TYPE INT(10) NOT NULL,
    USERNAME VARCHAR(255) NOT NULL
);

INSERT INTO JOB8 (ID, VERSION, CDI_FILE, EXTERNAL_JOB_ID, HIDDEN, JOB_DIR, NAME, NUM_TIME_STEPS, PERCENTAGE, POWERFLOW_VERSION, RANK, SUBMISSION_TIME, SUMMARY_FLAG, TIME_STEP, TIME_TO_FINISH, TIME_TO_START, TYPE, USERNAME) VALUES 
    (1, 0, 'k', 1, false, 'k', 'k', 2, 1, 'jj', 1, '2014-06-09 00:00:00.0', false, 0, 99.0, 55.0, 1, 'gg');

INSERT INTO JOB8 (ID, VERSION, CDI_FILE, EXTERNAL_JOB_ID, HIDDEN, JOB_DIR, NAME, NUM_TIME_STEPS, PERCENTAGE, POWERFLOW_VERSION, RANK, SUBMISSION_TIME, SUMMARY_FLAG, TIME_STEP, TIME_TO_FINISH, TIME_TO_START, TYPE, USERNAME) VALUES 
    (2, 1, 'tt1', 1, false, 'ff', 'tg', 7, 1, 'jjj', 1, '2014-06-08 00:00:00.0', false, 0, 78.0, 34.0, 1, 'hjj');

INSERT INTO JOB8 (ID, VERSION, CDI_FILE, EXTERNAL_JOB_ID, HIDDEN, JOB_DIR, NAME, NUM_TIME_STEPS, PERCENTAGE, POWERFLOW_VERSION, RANK, SUBMISSION_TIME, SUMMARY_FLAG, TIME_STEP, TIME_TO_FINISH, TIME_TO_START, TYPE, USERNAME) VALUES 
    (4, 0, 'k', 1, false, 'k', 'k', 2, 1, 'jj', 1, '2014-06-07 00:00:00.0', false, 0, 99.0, 55.0, 1, 'gg');

INSERT INTO JOB8 (ID, VERSION, CDI_FILE, EXTERNAL_JOB_ID, HIDDEN, JOB_DIR, NAME, NUM_TIME_STEPS, PERCENTAGE, POWERFLOW_VERSION, RANK, SUBMISSION_TIME, SUMMARY_FLAG, TIME_STEP, TIME_TO_FINISH, TIME_TO_START, TYPE, USERNAME) VALUES 
    (5, 1, 'tt1', 1, false, 'ff', 'tg', 5, 1, 'jjj', 1, '2014-05-29 00:00:00.0', false, 0, 78.0, 34.0, 1, 'hjj');

INSERT INTO JOB8 (ID, VERSION, CDI_FILE, EXTERNAL_JOB_ID, HIDDEN, JOB_DIR, NAME, NUM_TIME_STEPS, PERCENTAGE, POWERFLOW_VERSION, RANK, SUBMISSION_TIME, SUMMARY_FLAG, TIME_STEP, TIME_TO_FINISH, TIME_TO_START, TYPE, USERNAME) VALUES 
    (6, 0, 'cdi file1', 1, false, 'jd2', 'n3', 1, 1, 'pv4', 1, '2014-05-19 00:00:00.002', false, 0, 12.0, 345.0, 1, 'usn11');

INSERT INTO JOB8 (ID, VERSION, CDI_FILE, EXTERNAL_JOB_ID, HIDDEN, JOB_DIR, NAME, NUM_TIME_STEPS, PERCENTAGE, POWERFLOW_VERSION, RANK, SUBMISSION_TIME, SUMMARY_FLAG, TIME_STEP, TIME_TO_FINISH, TIME_TO_START, TYPE, USERNAME) VALUES 
    (7, 0, 'k', 1, false, 'k', 'k', 2, 1, 'jj', 1, '2014-04-09 00:00:00.0', false, 0, 99.0, 55.0, 1, 'gg');

INSERT INTO JOB8 (ID, VERSION, CDI_FILE, EXTERNAL_JOB_ID, HIDDEN, JOB_DIR, NAME, NUM_TIME_STEPS, PERCENTAGE, POWERFLOW_VERSION, RANK, SUBMISSION_TIME, SUMMARY_FLAG, TIME_STEP, TIME_TO_FINISH, TIME_TO_START, TYPE, USERNAME) VALUES 
    (8, 0, 'tt1', 1, false, 'ff', 'tg', 1, 1, 'jjj', 1, '2014-04-15 00:00:00.0', false, 0, 78.0, 34.0, 1, 'hjj');

INSERT INTO JOB8 (ID, VERSION, CDI_FILE, EXTERNAL_JOB_ID, HIDDEN, JOB_DIR, NAME, NUM_TIME_STEPS, PERCENTAGE, POWERFLOW_VERSION, RANK, SUBMISSION_TIME, SUMMARY_FLAG, TIME_STEP, TIME_TO_FINISH, TIME_TO_START, TYPE, USERNAME) VALUES 
    (9, 0, 'cdi file1', 1, false, 'jd2', 'n3', 1, 1, 'pv4', 1, '2014-02-09 00:00:00.0', false, 0, 12.0, 345.0, 1, 'usn11');

INSERT INTO JOB8 (ID, VERSION, CDI_FILE, EXTERNAL_JOB_ID, HIDDEN, JOB_DIR, NAME, NUM_TIME_STEPS, PERCENTAGE, POWERFLOW_VERSION, RANK, SUBMISSION_TIME, SUMMARY_FLAG, TIME_STEP, TIME_TO_FINISH, TIME_TO_START, TYPE, USERNAME) VALUES 
    (11, 0, 'k', 1, false, 'k', 'k', 2, 1, 'jj', 1, '2014-01-09 00:00:00.0', false, 0, 99.0, 55.0, 1, 'gg');

INSERT INTO JOB8 (ID, VERSION, CDI_FILE, EXTERNAL_JOB_ID, HIDDEN, JOB_DIR, NAME, NUM_TIME_STEPS, PERCENTAGE, POWERFLOW_VERSION, RANK, SUBMISSION_TIME, SUMMARY_FLAG, TIME_STEP, TIME_TO_FINISH, TIME_TO_START, TYPE, USERNAME) VALUES 
    (12, 0, 'tt1', 1, false, 'ff', 'tg', 1, 1, 'jjj', 1, '2014-02-09 00:00:00.0', false, 0, 78.0, 34.0, 1, 'hjj');

INSERT INTO JOB8 (ID, VERSION, CDI_FILE, EXTERNAL_JOB_ID, HIDDEN, JOB_DIR, NAME, NUM_TIME_STEPS, PERCENTAGE, POWERFLOW_VERSION, RANK, SUBMISSION_TIME, SUMMARY_FLAG, TIME_STEP, TIME_TO_FINISH, TIME_TO_START, TYPE, USERNAME) VALUES 
    (13, 0, 'cdi file1', 1, false, 'jd2', 'n3', 1, 1, 'pv4', 1, '2014-01-19 00:00:00.0', false, 0, 12.0, 345.0, 1, 'usn11');

INSERT INTO JOB8 (ID, VERSION, CDI_FILE, EXTERNAL_JOB_ID, HIDDEN, JOB_DIR, NAME, NUM_TIME_STEPS, PERCENTAGE, POWERFLOW_VERSION, RANK, SUBMISSION_TIME, SUMMARY_FLAG, TIME_STEP, TIME_TO_FINISH, TIME_TO_START, TYPE, USERNAME) VALUES 
    (33, 0, 'cdi file1', 1, false, 'jd2', 'n3', 1, 1, 'pv4', 1, '2014-03-09 00:00:00.0', false, 0, 12.0, 345.0, 1, 'usn11');


---
--- Primary Keys: 
---

ALTER TABLE PUBLIC.JOB8 ADD CONSTRAINT CONSTRAINT_2 PRIMARY KEY (ID);


---
--- Foreign Keys: 
---


